name: Build for MacOS Platforms

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        arch: [arm64]
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up CMake
      uses: lukka/get-cmake@latest

    - name: Install dependencies
      run: |
        if [[ ${{ matrix.os }} == 'macos-latest' ]]; then
          brew install qt curl openssl
          echo "CMAKE_PREFIX_PATH=$(brew --prefix qt):$(brew --prefix openssl):$(brew --prefix curl)" >> $GITHUB_ENV
        fi

    - name: Correction Moc
      run: echo "#include "mainwindow_moc.cpp"">> src/mainwindow.cpp

    - name: Sed hosts
      run: |
        rm -f src/data/hostlist && echo "api.example.com">> src/data/hostlist
        sed -i '' 's/skin\.example\.org/skin\.example\.com/g' src/include/network.h

    - name: Test Compiler
      run: |
        g++ -o test test.cpp
        ./test

    - name: Cp Cmake file
      run: cp CmakeListsAutoMoc.txt CmakeLists.txt

    - name: Set build dir
      run: mkdir build

    - name: Configure CMake
      working-directory: build
      run: cmake .. -DCMAKE_PREFIX_PATH=$CMAKE_PREFIX_PATH -DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_BUNDLE=ON

    - name: Build
      working-directory: build
      run: cmake --build . --config Release

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: build/
