name: Build for Multiple Platforms

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        arch: [x64, arm64]
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up CMake
      uses: lukka/get-cmake@latest

    - name: Install dependencies
      run: |
        if [[ ${{ matrix.os }} == 'macos-latest' ]]; then
          brew install qt curl openssl
          echo "CMAKE_PREFIX_PATH=$(brew --prefix qt):$(brew --prefix openssl):$(brew --prefix curl)" >> $GITHUB_ENV
        fi

    - name: Verify dependencies
      run: |
        if [[ ${{ matrix.os }} == 'macos-latest' ]]; then
          brew list qt && brew list curl && brew list openssl
        fi
      
    - name: Cp Cmake file
      run: cp CmakeListsCopy.txt CmakeLists.txt

    - name: Set build dir
      run: mkdir build

    - name: Configure CMake
      working-directory: build
      run: cmake .. -DCMAKE_PREFIX_PATH=$CMAKE_PREFIX_PATH

    - name: Build
      working-directory: build
      run: cmake --build . --config Release
